# Generated by Django 5.2.5 on 2025-08-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='stock cound'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Online Availability'),
        ),
    ]
